#!/bin/bash
export DISPLAY=:0

# Get VideoCard name
VIDEOCARDNAME=`xrandr | grep -w connected | /usr/bin/awk '{print $1}'`

# Run Game
/usr/games/mamearcade64 -inipath /etc/mame $1 &> /tmp/groovy_debug.txt 

# Get resolution name generated by GroovyMame switchres
RESOLUTION=`xrandr | grep GM- | /usr/bin/awk '{print $1}'` &>> /tmp/groovy_debug.txt  

# Switchback resolution to Attract Mode
xrandr --output $VIDEOCARDNAME --mode 640x480 &>> /tmp/groovy_debug.txt

# GroovyMame BugFix - Remove Modeline generated by it
echo "xrandr --rmmode $RESOLUTION" &>> /tmp/groovy_debug.txt  
xrandr --rmmode $RESOLUTION &>> /tmp/groovy_debug.txt  

